language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-$CI_VERSION.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
- cp /etc/sbt/sbtopts .sbtopts; echo "-Dsbt.global.base=$TRAVIS_BUILD_DIR/ci" >> .sbtopts
script:
- sbt test package assembly
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8bb2dc7129676dfd8ab9
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - CI_VERSION=3.3.1-20161112085142-c2c258a
  - secure: acmFu/OTy91q+AfP6bIZGVzTrtEMdO3onOwl0YiG/aG+Ugc6O54Gzx8MxLDKP6IvaeJ348+zL+39JHXvk2Nn5d1OiNG6MwPzM5hZmJJDCBkG9ezP8ThZaLp6bGUW1jU9nVAydqzEWZlKzhN28nSWNPdc+8eu7Cwo7gQyKLOf1m8=
