language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; assembly'
- ci/sbt-deploy.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8bb2dc7129676dfd8ab9
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: lHFlo9U1E4PU+P6BpgBtra0370gRBZY412AgwJlsyN1FZaaXbl19BHY1TWPj4dl0/ELj1LwpCuMKufUKb3DhKc480/ipYvK71FAom4uFe1m8pP3nIHI/4tJBh91aTVFhQ38pN3ne+T7HudDlAbQfNHqxp1rluse3CY/4oRXFrck=
before_install:
- openssl aes-256-cbc -K $encrypted_2911a079a7e8_key -iv $encrypted_2911a079a7e8_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
