language: scala
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-$CI_VERSION.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
- cp /etc/sbt/sbtopts .sbtopts; echo "-Dsbt.global.base=$TRAVIS_BUILD_DIR/ci" >> .sbtopts
script:
- sbt test package assembly
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8bb2dc7129676dfd8ab9
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - CI_VERSION=3.6.0-20170704005122-ec7202f
  - secure: WRp53VqVPzEpdwh8W1wDJdvmzLuVjGzckdk9x3M3Qe8LOHV78YaofKr/GaXBqKit4DiKb9UIxS8Ab52RHxRlEtw0B3SzI1lzZUROeL4iPn8P7e0fnRwiBY7Mnj+aYh1G7e9F1mkPNaW7F3EOXqpXRwU3650uo6Lri65WmQ9mDVk=
  - secure: d56QSqOPcVyZgGbnb9OdTLYFYe72Ou2Vjenhb2QVQYp7u0WpfCxMFJsHoj3OGfFwg9tkrKaVB6CpGpQOkCs22h2KBU3o+RWhuTPfH+1pCW/oxOUXLV7PHR3c1xIgM6Wjh81g5+f1bK0ZzatEFEn+m6TMQFP/7yNC27VHaz0Ithk=
